<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Hyvä Compatibility module for PayZen. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

declare(strict_types=1);
?>
<div class="payzen-gift" style="margin-bottom: 25px; width: 100%; padding: 12px 0px 12px 25px;">
    <fieldset style="padding-top: 10px;">
        <div class="field">
            <ul class="payzen-gift-payment-option payzen-payment-option" style="padding: 0;">
                <?php
                $cards = $block->getAvailableCcTypes();
                $single = count($cards) === 1;
                if ($single) : ?>
                <label>
                    <span><?= $escaper->escapeHtml(__("Your means of payment")); ?></span>
                </label>
                <?php else : ?>
                <label>
                    <span><?= $escaper->escapeHtml(__("Choose your means of payment")); ?></span>
                </label>
                <?php endif;
                // Show card logos as radio buttons.
                $first = true;
                foreach ($cards as $code => $label) : ?>
                <li style="display: inline-block; padding-right: 20px; padding-bottom: 6px;">
                    <?php
                    if ($single) : ?>
                    <input type="hidden"
                           id="payzen_gift_cc_type_' <?= $escaper->escapeHtml($code); ?>"
                           value="<?= $escaper->escapeHtml($code); ?>"
                           name="payment[payzen_gift_cc_type]" />
                    <?php else : ?>
                    <input type="radio"
                           class="radio"
                           id="payzen_gift_cc_type_<?= $escaper->escapeHtml($code); ?>"
                           <?php if ($first) : ?> checked="checked"<?php endif; ?>
                           value="<?= $escaper->escapeHtml($code); ?>"
                           name="payment[payzen_gift_cc_type]" />
                    <?php endif;

                    $first = false;
                    $ccImageSrc = $block->getCcTypeImageSrc($code);

                    $label = $ccImageSrc ? '<img alt="' . $block->escapeHtml($label) . '"
                                                 src="' . $block->escapeHtml($ccImageSrc) . '"
                                                 title="' . $block->escapeHtml($label) . '"
                                                 style="max-height: 35px; max-width: 90px;
                                                 vertical-align: middle;"/>'
                            : "<span>" . $block->escapeHtml($label) . "</span>"; ?>

                    <label for="payzen_gift_cc_type_<?= $escaper->escapeHtml($code) ?>"><?php echo $label; ?></label>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </fieldset>
</div>