<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Hyvä Compatibility module for PayZen. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

declare(strict_types=1);
?>

<div class="payzen-multi" style="margin-bottom: 25px; width: 100%; padding: 12px 0px 12px 25px;">
    <fieldset style="padding-top: 10px;">
        <div class="field">
            <?php
            $first = true;
            $options = $block->getAvailableOptions();
            $oneOption = count($options) === 1;

            if ($oneOption) : ?>
            <label>
                <span><?= $escaper->escapeHtml(__("Your payment option")); ?></span>
            </label>
            <?php  else : ?>
            <label>
                <span><?= $escaper->escapeHtml(__("Choose your payment option")); ?></span>
            </label>
            <?php endif; ?>
            <ul class="payzen-multi-options payzen-payment-option">
                <?php
                foreach ($options as $key => $option) : ?>
                <li style="display: inline-block; padding-right: 20px; padding-bottom: 6px;">
                    <?php if ($oneOption) : ?>
                    <input type="hidden"
                           id="option_<?= $escaper->escapeHtml($key); ?>"
                           value="<?= $escaper->escapeHtml($key); ?>"
                           name="payment[payzen_multi_option]" />
                    <?php  else : ?>
                    <input class="radio"
                           type="radio"
                           <?php if ($first) : ?> checked="checked"<?php endif; ?>
                           id="option_<?= $escaper->escapeHtml($key); ?>"
                           value="<?= $escaper->escapeHtml($key); ?>"
                           name="payment[payzen_multi_option]" />
                    <?php
                        $first = false;
                    endif;
                    ?>

                    <label style="float: none;"><?= $escaper->escapeHtml($option['label']); ?></label>
                    <br style="margin-bottom: 5px;" />
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php
        if ($block->isLocalCcType()) :
            echo $this->getLayout()->createBlock("\Lyranetwork\PayzenHyva\Block\Checkout\Payment\Method\Multi")->setTemplate("Lyranetwork_PayzenHyva::component/payment/method/ccType.phtml")->toHtml(); ?>
    <?php endif; ?>
    </fieldset>
</div>