<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Hyvä Compatibility module for PayZen. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

declare(strict_types=1);

?>
<script>
    const PAYZEN_STANDARD = 'payzen_standard';
    const PAYZEN_PLACE_ORDER_BUTTON = '.btn-primary[x-bind="buttonPlaceOrder"]';
    var PAYZEN_PLACE_ORDER = true; // An order can be placed (created).
    var PAYZEN_REFRESH_TOKEN = true;
    var PAYZEN_MOBILE_CHECKOUT = false;
    var PAYZEN_SELECTED_METHOD = false;
    var PAYZEN_IS_POPIN = false;

    /**
     * trigger form token update if address data or shipping method changes.
     */
    function handleDataUpdated() {
        const paymentMethodCode = (hyvaCheckout?.payment?.getActive()?.getCode());

        if (paymentMethodCode && (PAYZEN_REFRESH_TOKEN === true)) {
            updateFormToken();
        }
    }

    /**
     *  Select our method by default if it's the only one available.
     */
    function selectByDefault() {
        paymentMethods = document.getElementsByName('payment-method-option');
        if ((paymentMethods.length == 1) && (paymentMethods[0].value == PAYZEN_STANDARD)) {
            let displayTitle = document.getElementById('payzen_display_title');
            if (displayTitle && (displayTitle.value == "0")) {
                let element = document.querySelector('#payment-method-option-' + PAYZEN_STANDARD + ' label.cursor-pointer');

                if (element) {
                    element.classList.add("payzen-hide-element");
                    element.style.visibility = 'hidden';
                    element.style.height = '0';
                }
            }

            if (! document.querySelector('input[name="payment-method-option"]:checked')) {
                document.getElementById('payment-method-' + PAYZEN_STANDARD).click();
            }
        }
    }

    window.addEventListener('magewire:load', () => {
        Magewire.on('shipping_address_saved', handleDataUpdated);
        Magewire.on('billing_address_saved', handleDataUpdated);
        Magewire.on('shipping_address_activated', handleDataUpdated);
        Magewire.on('billing_address_activated', handleDataUpdated);
        Magewire.on('shipping_method_selected', handleDataUpdated);
        Magewire.on('coupon_code_applied', handleDataUpdated);
        Magewire.on('coupon_code_revoked', handleDataUpdated);
    }, { once: true });

    window.addEventListener('magewire:update', event => {
        let payzenEavFields = document.querySelectorAll('[class*="field-payzen"]');
        payzenEavFields.forEach(element => element.remove());

        selectByDefault();
        hideSmartformButton('0');

        var restForm = document.getElementById('payzen_rest_form');
        if (! restForm) {
            return;
        }

        if (hyvaCheckout.config.getValue('navigator.checkout.name') == 'mobile') {
            PAYZEN_MOBILE_CHECKOUT = true;
            let step = hyvaCheckout.navigation.getCurrent().name;

            if (step == 'payment') {
                return;
            }

            if (sessionStorage.getItem('payzen_payment_method') != PAYZEN_STANDARD) {
                return;
            }

            if ((PAYZEN_REFRESH_TOKEN === true) && (PAYZEN_PLACE_ORDER === true)) {
                updateFormToken();
            }
        } else {
            let method = (hyvaCheckout?.payment?.getActive()?.getCode());
            if (! method || method !== PAYZEN_STANDARD) {
                return;
            }
        }
    });

    /**
     * Display embedded fields on checkout.
     */
    document.addEventListener('livewire:load', function() {
        let payzenEavFields = document.querySelectorAll('[class*="field-payzen"]');
        payzenEavFields.forEach(element => element.remove());

        selectByDefault();
        hideSmartformButton('0');

        var restForm = document.getElementById('payzen_rest_form');
        if (! restForm) {
            return;
        }

        method = (hyvaCheckout?.payment?.getActive()?.getCode());
        if (! method) {
            method = sessionStorage.getItem('payzen_payment_method');
            if (method == PAYZEN_STANDARD) {
                window.dispatchEvent(new CustomEvent('checkout:payment:method-activate', {
                    detail: { method: PAYZEN_STANDARD },
                }));

                return;
            }
        }

        if (! method || method !== PAYZEN_STANDARD) {
            return;
        }

        if (PAYZEN_REFRESH_TOKEN === true) {
            updateFormToken();
        }
    });

    /**
     * trigger form update if address data change.
     */
    window.addEventListener('checkout:payment:method-activate', event => {
        const tempMethod = event?.detail?.method;
        const method = (typeof tempMethod === 'string' ? tempMethod : '') ?? '';

         if ((typeof (KR) == 'undefined') || (method !== PAYZEN_STANDARD)) {
            sessionStorage.removeItem('payzen_payment_method');

            let activeMethod = hyvaCheckout?.payment?.getActive()?.getCode();
            if (activeMethod && (activeMethod == PAYZEN_STANDARD)) {
                hyvaCheckout.payment.method = null;
            }

            if (method !== PAYZEN_STANDARD) {
                return;
            }
        }

        if (document.getElementById('payzen-standard-id')) {
            document.getElementById('payzen-standard-id').addEventListener("click", (event) => {
                payzenStandardUpdateBlock('id');
            });

            document.getElementById('payzen-standard-cc').addEventListener("click", (event) => {
                payzenStandardUpdateBlock('cc');
            });

            function payzenStandardUpdateBlock(blockId) {
                let fields = document.querySelectorAll('[class*="payzen-standard-' + blockId + '-block"]');
                fields.forEach(element => element.style.display = 'none');

                fields = document.querySelectorAll('[class*="payzen-standard-' + (blockId == 'id' ? 'cc' : 'id') + '-block"]');
                fields.forEach(element => element.style.display = 'block');
                document.querySelector('input[name="payment[payzen_standard_use_identifier]"]').value = (blockId == 'id' ? '0' : '1');
            }
        }

        hyvaCheckout.payment.activate(PAYZEN_STANDARD, {
            async placeOrder() {
                if (typeof (KR) === 'undefined') {
                    return;
                }

                let component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                component.setLogSrc("Magento Submit Button");

                let IS_CARD_EXTENDED = KR.$store.getters.cardsFormExpanded && (PAYZEN_SELECTED_METHOD == 'CARDS');
                if (IS_CARD_EXTENDED) {
                    // Expanded card form is selected, let's check form validity.
                    KR.validateForm().then(function(v) {
                        submitPayment();
                    }).catch(function(v) {
                        var result = v.result;

                        return result.doOnError();
                    });
                } else {
                    submitPayment();
                }
            },

            async validate() {
                if (typeof (KR) !== 'undefined') {
                   sessionStorage.setItem('payzen_payment_method', PAYZEN_STANDARD);
                   return true;
                }

                let component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');

                let ccType = document.querySelector('input[name="payment[payzen_standard_cc_type]"]:checked')?.value;
                if (typeof ccType == 'undefined') {
                    ccType = document.querySelector('input[name="payment[payzen_standard_cc_type]"]')?.value;
                }

                let identifier = document.querySelector('input[name="payment[payzen_standard_use_identifier]"]')?.value;

                let paymentData = {
                    payzen_standard_cc_type : ccType,
                    payzen_standard_use_identifier: identifier
                }

                return new Promise(async (resolve) => {
                    component.setAdditionalInformation(paymentData).then(() => {
                        resolve(true);
                    });
                });


            },

            isVisibleInStep() {
                return true;
            },

            placeOrderViaJs() {
                return (typeof (KR) !== 'undefined');
            }
        });

        if (PAYZEN_REFRESH_TOKEN === true) {
            updateFormToken();
        }
    });

    function submitPayment() {
        PAYZEN_REFRESH_TOKEN = false;

        // Place the order.
        if (PAYZEN_PLACE_ORDER === true) {
            hyvaCheckout.main.getWireComponent().placeOrder()
            .then(() => {
                return hyvaCheckout.config.isSetFlag('navigator.finished') || false
            }).then(async result => {
                if (result) {
                    PAYZEN_PLACE_ORDER = false;
                    setOrderToken();
                }
            });
        } else if (PAYZEN_PLACE_ORDER === false) {
            submitKR();
        }
    }

    function hideSmartformButton(restPopin) {
        if (restPopin === "1") {
            var element = document.getElementsByClassName("kr-smart-form kr-smart-form-wrapper.kr-type-popin kr-smart-form-modal-button");
            if (element.length > 0) {
                element[0].classList.add("payzen-hide-element");
                element[0].style.visibility = 'hidden';
                element[0].style.height = '0';
            }
        }

        var element = document.getElementsByClassName("kr-smart-form-single-payment-button");
        if (element && element.length > 0) {
            element[0].classList.add("payzen-hide-element");
            element[0].style.visibility = 'hidden';
            element[0].style.height = '0';
            element[0].disabled = true;

            let span = element[0].querySelector("span");
            if (span) {
                span.style.height = '0';
                span.style.visibility = 'hidden';
            }
        }
    }

    function updateFormToken() {
        if (typeof (KR) == 'undefined') {
            return;
        }

        var restForm = document.getElementById('payzen_rest_form');
        if (! restForm) {
            return;
        }

        PAYZEN_REFRESH_TOKEN = false;

        var popin = document.getElementsByClassName('kr-popin-button');
        if (popin.length == 0) {
            hyvaCheckout.loader.start();
            window.dispatchEvent(new CustomEvent('magewire:loader:start'));
        }

        return new Promise(async (resolve, reject) => {
            let component;

            try {
                component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
            } catch (error) {
                await Livewire.onLoad(() => {
                    component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                })
            }

            if (document.querySelector(PAYZEN_PLACE_ORDER_BUTTON)) {
                document.querySelector(PAYZEN_PLACE_ORDER_BUTTON).disabled = true;
            }

            await component.getPaymentData(PAYZEN_STANDARD);

            let data = component.paymentData;
            PAYZEN_IS_POPIN = (data['restPopin'] === '1');

            if (typeof data['restFormToken'] === 'undefined' || data['restFormToken'] === false) {
                let element = document.querySelector(PAYZEN_PLACE_ORDER_BUTTON)
                if (element) {
                    element.disabled = true;
                }

                document.getElementById('payzen_error_message').innerHTML = data['errorMessage'];
                document.getElementById('payzen_standard_message').style.display = 'block';

                await KR.removeForms();

                PAYZEN_REFRESH_TOKEN = true;
                window.dispatchEvent(new CustomEvent('magewire:loader:done'));
                resolve(false);

                return;
            }

            if (document.getElementById('payzen_standard_message')) {
                document.getElementById('payzen_error_message').innerHTML = '';
                document.getElementById('payzen_standard_message').style.display = 'none';
            }

            var payzenFormConfig = { formToken: data['restFormToken'], language: data['language'], smartForm: { visibility: false } };
            if (data['compactMode'] === "1") {
                payzenFormConfig['cardForm'] = { layout: 'compact' };
                payzenFormConfig['smartForm']['layout'] = 'compact';
            }

            if (data['groupThreshold'] && !isNaN(data['groupThreshold'])) {
                payzenFormConfig['smartForm']['groupingThreshold'] = data['groupThreshold'];
            }

            try {
                if (data['customerWallet'] == '1') {
                    await KR.removeForms();
                    let skeletonWrapper = document.querySelectorAll('[class*="kr-skeleton-wrapper"]');
                    skeletonWrapper.forEach(element => element.remove());
                }

                const v = await KR.setFormConfig(payzenFormConfig);
                window.dispatchEvent(new CustomEvent('magewire:loader:done'));

                KR = v.KR;

                await KR.onError(function (e) {
                    manageError(e)
                });

                await KR.onFormReady(async () => {
                    hideSmartformButton(data['restPopin']);

                    if (document.querySelector(PAYZEN_PLACE_ORDER_BUTTON)) {
                        document.querySelector(PAYZEN_PLACE_ORDER_BUTTON).disabled = false;
                    }

                    await KR.smartForm.onClick((data) => {
                        if (data.action === "methodSelected") {
                            PAYZEN_SELECTED_METHOD = data.paymentMethod;
                            return true;
                        }

                        if (PAYZEN_PLACE_ORDER === true) {
                            component.setLogSrc("Smartform Native Button");
                            submitPayment(KR);

                            return false;
                        } else if (PAYZEN_PLACE_ORDER === false) {
                            component.setLogSrc("Smartform Native Button | PLACE_ORDER false");
                            return true;
                        }

                        component.setLogSrc("Smartform Native Button | PLACE_ORDER undefined or null");
                        return false;
                    });
                });

                resolve(true);
                PAYZEN_REFRESH_TOKEN = true;
            } catch (e) {
                window.dispatchEvent(new CustomEvent('magewire:loader:done'));
                reject();

                return manageError(e);
            };
        });
    }

    function manageError(e) {
        PAYZEN_REFRESH_TOKEN = true;

        if (PAYZEN_PLACE_ORDER === true) {
            return false;
        }

        hyvaCheckout.navigation.enableButtonPlaceOrder();

        let element = document.querySelector(PAYZEN_PLACE_ORDER_BUTTON);
        if (element) {
            element.disabled = false;
        }

        hideSmartformButton('0');

        let component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
        component.restoreCart().then(() => {
            console.log('Cart restored.');

            return true;
        });
    }

    function setOrderToken() {
        return new Promise(async (resolve, reject) => {
            let component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
            component.setOrderToken().then(() => {
                hyvaCheckout.navigation.disableButtonPlaceOrder();

                let data = component.paymentData;
                if (data['restFormToken'] == false) {
                    let element = document.querySelector(PAYZEN_PLACE_ORDER_BUTTON);
                    if (element) {
                        element.disabled = true;
                    }

                    resolve(false);

                    return;
                }

                var payzenFormConfig = { formToken: data['restFormToken'], language: data['language'], smartForm: { visibility: false } };
                if (data['compactMode'] === "1") {
                    payzenFormConfig['cardForm'] = { layout: 'compact' };
                    payzenFormConfig['smartForm']['layout'] = 'compact';
                }

                if (data['groupThreshold'] && !isNaN(data['groupThreshold'])) {
                    payzenFormConfig['smartForm']['groupingThreshold'] = data['groupThreshold'];
                }

                KR.setFormConfig(
                    payzenFormConfig
                ).then(
                    function(v) {
                        resolve(true);
                        KR = v.KR;

                        KR.onPopinClosed(function(e) {
                            manageError(e)
                        });

                        KR.onFormReady(() => {
                            submitKR();

                            hideSmartformButton(data['restPopin']);
                        });

                        KR.onError(function(e) {
                            if (!e.metadata.hasOwnProperty('answer')) {
                                return manageError(e);
                            }

                            // Ajax call to update order status.
                            if (data['updateOrder'] == "1") {
                                var answer = e.metadata.answer;
                                var krResponse =  {
                                    'kr-answer-type': 'V4/Payment',
                                    'kr-answer': JSON.stringify(answer.clientAnswer),
                                    'kr-hash': answer.hash,
                                    'kr-hash-algorithm': answer.hashAlgorithm,
                                    'payzen_update_order': '1'
                                };

                                fetch(data['restReturnUrl'], {
                                    method: "POST",
                                    headers: {
                                        'Content-Type': 'application/x-www-form-urlencoded',
                                        'X-Requested-With': 'XMLHttpRequest'
                                    },
                                    body: new URLSearchParams(krResponse).toString(),
                                }).finally(() => {
                                    resolve(false);

                                    return manageError(e);
                                })
                            } else {
                                resolve(false);

                                return manageError(e);
                            }
                        });
                    }
                 ).catch(function (e) {
                     reject();
                     return manageError(e);
                 });
             });
        });
    }

    function submitKR() {
        if (PAYZEN_IS_POPIN === true) {
            KR.openPopin();
        } else {
            KR.openSelectedPaymentMethod();
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>